name: Test

on: [push]

jobs:
  build:
    #runs-on: ubuntu-20.04
    runs-on: windows-2022
    steps:
    - name: checksum
      run: |
        links=( \
            https://github.com/KhronosGroup/MoltenVK/archive/refs/tags/v1.2.1.tar.gz \
        )
        for link in ${links[@]}; do
            wget -q $link
        done
        ls -l
        shasum -a 256 *
