name: Test

on: [push]

jobs:
  build:
   runs-on: ubuntu-22.04
   steps:
    - name: checksum
      run: |
        links=( \
            https://github.com/libsdl-org/SDL/releases/download/release-2.28.0/SDL2-2.28.0.tar.gz \
        )
        for link in ${links[@]}; do
            wget -q $link
        done
        ls -l
        shasum -a 256 *
