name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checksum
      run: |
        links=( \
            https://github.com/coelckers/ZMusic/archive/refs/tags/1.1.10.tar.gz \
        )
        for link in ${links[@]}; do
            wget -q $link
        done
        ls -l
        shasum -a 256 *

#     runs-on: macos-12
#     steps:
#     - name: Build MoltenVK
#       run: |
#         curl -JOL https://github.com/KhronosGroup/MoltenVK/archive/refs/tags/v1.1.10.tar.gz
#         tar -xf MoltenVK-1.1.10.tar.gz
#         cd MoltenVK-1.1.10
#         ./fetchDependencies --macos
#         make macos
#         ls -lR .
