name: Test

on: [push]

jobs:
  build:
   runs-on: ubuntu-22.04
   steps:
    - name: checksum
      run: |
        links=( \
            https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/8.1.0/graphviz-8.1.0.tar.gz \
        )
        for link in ${links[@]}; do
            wget -q $link
        done
        ls -l
        shasum -a 256 *
