name: Test

on: [push]

jobs:
  build:
    # runs-on: ubuntu-22.04
    # steps:
    #   - name: checksum
    #     run: |
    #       links=( \
    #         https://github.com/libsndfile/libsndfile/releases/download/1.2.2/libsndfile-1.2.2.tar.xz \
    #       )
    #       for link in ${links[@]}; do
    #         wget -q $link
    #       done
    #       ls -l
    #       shasum -a 256 *

    runs-on: macos-12
    steps:
      - name: Vulkan-Loader 1.3.261 macOS cross-compilation
        run: |
          curl -JOL 'https://github.com/leetal/ios-cmake/raw/547143849a0965813c40e3a8db286edf1d7667f2/ios.toolchain.cmake'
          
          curl -JOL 'https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/v1.3.261.tar.gz'
          tar -xf Vulkan-Headers-1.3.261.tar.gz
          cd Vulkan-Headers-1.3.261
          cmake -DCMAKE_TOOLCHAIN_FILE=../ios.toolchain.cmake -DPLATFORM=MAC_ARM64 -DCMAKE_INSTALL_PREFIX=../vkheaders-install -B build -S .
          cd build
          make install
          cd ../..
          
          curl -JOL 'https://github.com/KhronosGroup/Vulkan-Loader/archive/refs/tags/v1.3.261.tar.gz'
          tar -xf Vulkan-Loader-1.3.261.tar.gz
          cd Vulkan-Loader-1.3.261
          cmake -DCMAKE_TOOLCHAIN_FILE=../ios.toolchain.cmake -DPLATFORM=MAC_ARM64 -DVulkanHeaders_DIR=../vkheaders-install/share/cmake/VulkanHeaders -B build -S .
          cd build
          make

      # - name: build quakespasm .pak file
      #   run: |
      #     git clone --depth=1 https://github.com/sezero/quakespasm.git
      #     cd quakespasm/Misc/qs_pak
      #     make

      # - name: upload quakespasm .pak file
      #   uses: actions/upload-artifact@v3
      #   with:
      #     path: quakespasm/Misc/qs_pak
      #     name: quakespasm-pak


#     runs-on: macos-12
#     steps:
#     - name: download
#       run: curl -JOL https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/8.1.0/graphviz-8.1.0.tar.gz
#
#     - name: extract
#       run: tar -xvf graphviz-8.1.0.tar.gz
#
#     - name: configure
#       working-directory: graphviz-8.1.0
#       run: ./configure --disable-dependency-tracking
#
#     - name: build
#       working-directory: graphviz-8.1.0
#       run: make -j3
#
#     - name: install
#       working-directory: graphviz-8.1.0
#       run: make DESTDIR=$(pwd)/../graphviz install
#
#     - name: list
#       run: ls -lR graphviz
#
#     - name: test
#       run: ./graphviz/usr/local/bin/dot --help
