name: Test

on: [push]

jobs:
  build:
   runs-on: ubuntu-22.04
   steps:
    - name: checksum
      run: |
        links=( \
            https://github.com/dfeneyrou/palanteer/archive/refs/tags/v0.6.tar.gz \
            https://github.com/dfeneyrou/palanteer/archive/91de90475571ce364b769693e6abd05c91e5163c.tar.gz \
        )
        for link in ${links[@]}; do
            wget -q $link
        done
        ls -l
        shasum -a 256 *
