name: Test

on: [push]

jobs:
  build:
#    runs-on: ubuntu-22.04
#    steps:
#     - name: checksum
#       run: |
#         links=( \
#             https://github.com/radareorg/radare2/archive/refs/tags/5.8.2.tar.gz \
#         )
#         for link in ${links[@]}; do
#             wget -q $link
#         done
#         ls -l
#         shasum -a 256 *

#    runs-on: macos-12
    runs-on: ubuntu-22.04
    steps:
    - name: radare2 meson
      run: |
        sudo apt install meson ninja-build
        curl -JOL 'https://github.com/radareorg/radare2/releases/download/5.8.4/radare2-5.8.4.tar.xz'
        tar -xf radare2-5.8.4.tar.xz
        export CC=clang
        export CXX=clang++
        export LDFLAGS=-fuse-ld=lld
        export LD=lld
        mkdir r2build
        meson setup --buildtype=release --default-library=static -Denable_tests=false r2build radare2-5.8.4
        meson compile -C=r2build --verbose
        meson install -C=r2build --destdir=../r2install
        ls -lR r2install
