name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: test
      run: |
        wget https://github.com/FluidSynth/fluidsynth/archive/refs/tags/v2.2.1.tar.gz
        ls -l
        shasum -a 256 *.tar.gz
