name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checksum
      run: |
        links=( \
            https://github.com/ZDoom/gzdoom/releases/download/g4.10.0/gzdoom_4.10.0_amd64.deb \
        )
        for link in ${links[@]}; do
            wget -q $link
        done
        # ls -l
        # shasum -a 256 *
        # dpkg -c gzdoom_4.10.0_amd64.deb
        sudo apt install libsdl2-2.0-0 libvorbisenc2 libflac8 libopus0 libmpg123-0 libmp3lame0
        sudo dpkg -i gzdoom_4.10.0_amd64.deb
        which gzdoom
