name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: checksum
      run: |
        links=( \
            https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.5/wxWidgets-3.0.5.tar.bz2 \
            https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.5.1/wxWidgets-3.0.5.1.tar.bz2 \
            https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.5/wxWidgets-3.1.5.tar.bz2 \
            https://www.sfml-dev.org/files/SFML-2.5.1-sources.zip \
            https://sourceforge.net/projects/freeimage/files/Source%20Distribution/3.18.0/FreeImage3180.zip \
            https://downloads.sourceforge.net/project/ftgl/FTGL%20Source/2.1.3~rc5/ftgl-2.1.3-rc5.tar.gz \
            https://github.com/nigels-com/glew/releases/download/glew-2.2.0/glew-2.2.0.tgz \
        )
        for link in ${links[@]}; do
            wget -q $link
        done
        ls -l
        shasum -a 256 *.tar.*
