name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: checksum
      run: |
        links=( \
            https://downloads.sourceforge.net/project/libjpeg-turbo/2.1.1/libjpeg-turbo-2.1.1.tar.gz \
        )
        for link in ${links[@]}; do
            wget -q $link
        done
        ls -l
        shasum -a 256 *
