name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: WTF is Strawberry
      shell: bash
      run: |
        ls -lR /c/Strawberry
   
#     - name: checksum
#       run: |
#         links=( \
#             https://github.com/ZDoom/ZMusic/archive/refs/tags/1.1.11.tar.gz \
#         )
#         for link in ${links[@]}; do
#             wget -q $link
#         done
#         ls -l
#         shasum -a 256 *
