name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install
      run: |
        sudo pip install --upgrade youtube_dl

    - name: list formats
      run: |
        youtube-dl -F https://www.youtube.com/watch?v=NvO5u5u3gn0
        youtube-dl -F https://www.youtube.com/watch?v=APLgqNx4sww
