name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: checksum
      run: |
        links=( \
            https://github.com/radareorg/radare2/archive/refs/tags/5.8.2.tar.gz \
            https://github.com/radareorg/radare2/releases/download/5.8.2/radare2-5.8.2.tar.xz \
            https://github.com/radareorg/radare2/releases/download/5.8.2/radare2-5.8.2.tar.xz.old.xz \
            https://github.com/radareorg/radare2/releases/download/5.8.2/radare2-x64-5.8.2.pkg \
        )
        for link in ${links[@]}; do
            wget -q $link
        done
        ls -l
        shasum -a 256 *
