name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: checksum
      run: |
        wget -q https://github.com/zlib-ng/zlib-ng/archive/refs/tags/2.0.4.tar.gz
        ls -l
        shasum -a 256 *.tar.*

    # - name: test
    #   run: |
    #     sudo apt update
    #     sudo apt list --upgradable
