name: Test

on: [push]

jobs:
  build:
    #runs-on: ubuntu-20.04
    runs-on: windows-2022
    steps:
    - name: Strawberry
      run: |
        $env:Path
   
    - name: Strawberry BASH
      shell: bash
      run: |
        export
        echo ---------------------
        export PATH=`echo $PATH | tr ":" "\n" | grep -v "Strawberry" | tr "\n" ":"`
        export
   
#     - name: checksum
#       run: |
#         links=( \
#             https://github.com/ZDoom/ZMusic/archive/refs/tags/1.1.11.tar.gz \
#         )
#         for link in ${links[@]}; do
#             wget -q $link
#         done
#         ls -l
#         shasum -a 256 *
