name: Test

on: [push]

jobs:
  build:
    runs-on: macos-12
    steps:
    - name: download
      run: curl -JOL https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/8.1.0/graphviz-8.1.0.tar.gz
      
    - name: extract
      run: tar -xvf graphviz-8.1.0.tar.gz
        
    - name: configure
      working-directory: graphviz-8.1.0
      run: ./configure --disable-dependency-tracking
        
    - name: build
      working-directory: graphviz-8.1.0
      run: make -j3
      
    - name: install
      working-directory: graphviz-8.1.0
      run: make DESTDIR=$(pwd)/../graphviz install
      
    - name: list
      run: ls -lR graphviz
      
    - name: test
      run: ./graphviz/usr/local/bin/dot --help
      
  
   # runs-on: ubuntu-22.04
   # steps:
   # - name: checksum
   #   run: |
   #     links=( \
   #         https://gitlab.com/graphviz/graphviz/-/archive/8.1.0/graphviz-8.1.0.tar.bz2 \
   #     )
   #     for link in ${links[@]}; do
   #         wget -q $link
   #     done
   #     ls -l
   #     shasum -a 256 *
