name: Test

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: "macOS"
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "TesT"
          }

    steps:
    - uses: actions/checkout@v1

    - name: Set
      run: |
        echo "::set-output name=project_name_lower::$(echo ${{ matrix.config.name }} | tr '[:upper:]' '[:lower:]')"

    - name: Get
      run: |
        echo "Value is ${{ steps.vars.outputs.project_name_lower }}"
