name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: libinstpatch
      run: |
        curl -JOL https://github.com/swami/libinstpatch/archive/v1.1.3.tar.gz
        shasum -a 256 libinstpatch-1.1.3.tar.gz

    - name: fluidsynth
      run: |
        curl -JOL https://github.com/FluidSynth/fluidsynth/archive/v2.1.1.tar.gz
        shasum -a 256 fluidsynth-2.1.1.tar.gz
