name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: dependencies
      run: |
        sudo apt install libsdl2-dev

    - name: test
      run: |
        sdl2-config --version --prefix --cflags --libs
        cd sdl_test
        cmake .
