name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: dependencies
      run: |
        sudo apt install libsdl2-dev

    - name: test
      run: |
        cd sdl_test
		cmake .
