name: Test

on: [push]

jobs:
  build:
   runs-on: ubuntu-22.04
   steps:
    - name: checksum
      run: |
        links=( \
            https://github.com/xiph/opus/releases/download/v1.4/opus-1.4.tar.gz \
        )
        for link in ${links[@]}; do
            wget -q $link
        done
        ls -l
        shasum -a 256 *
