name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: checksum
      run: |
        wget https://github.com/zlib-ng/zlib-ng/archive/refs/tags/2.0.3.tar.gz
        ls -l
        shasum -a 256 *.tar.gz

    - name: test
      run: |
        sudo apt update
        sudo apt list --upgradable
