name: Test

on: [push]

jobs:
  build:
   runs-on: ubuntu-22.04
   steps:
    - name: checksum
      run: |
        links=( \
            https://github.com/xiph/flac/releases/download/1.4.3/flac-1.4.3.tar.xz \
        )
        for link in ${links[@]}; do
            wget -q $link
        done
        ls -l
        shasum -a 256 *
