name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: checksum
      run: |
        links=( \
            https://openal-soft.org/openal-releases/openal-soft-1.22.1.tar.bz2 \
        )
        for link in ${links[@]}; do
            wget -q $link
        done
        ls -l
        shasum -a 256 *
