name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: checksum
      run: |
        links=( \
            https://github.com/FluidSynth/fluidsynth/archive/refs/tags/v2.2.7.tar.gz \
            https://github.com/libsdl-org/SDL/releases/download/release-2.0.22/SDL2-2.0.22.tar.gz \
        )
        for link in ${links[@]}; do
            wget -q $link
        done
        ls -l
        shasum -a 256 *
