name: Test

on: [push]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Visual Studio Test
      shell: pwsh
      run: |
        $vsroot = (Get-VisualStudioInstance).InstallationPath
        $devenv = join-path $vsroot 'Common7\IDE\devenv.com'
        Get-Date
        Start-Process -Wait $devenv -ArgumentList '/?'
        Get-Date

#    runs-on: ubuntu-22.04
#    steps:
#     - name: checksum
#       run: |
#         links=( \
#             https://downloads.sourceforge.net/project/libjpeg-turbo/3.0.0/libjpeg-turbo-3.0.0.tar.gz \
#         )
#         for link in ${links[@]}; do
#             wget -q $link
#         done
#         ls -l
#         shasum -a 256 *
