name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: gcc version
      run: |
        gcc --version
        g++ --version
    - name: checksum
      run: |
        links=( \
            https://github.com/bunder/qpakman/archive/refs/tags/v0.67.tar.gz \
        )
        for link in ${links[@]}; do
            wget -q $link
        done
        ls -l
        shasum -a 256 *
